$lang{ID}             = '#',
$lang{TYPE}           = 'Тип дерева',
$lang{LOGO}           = 'Список дерев',
$lang{ADD}            = 'Добавити',
$lang{CHANGE}         = 'Змінити',
$lang{SPECIES}        = 'Сорт',

$lang{ADD_TYPE}       = 'Добавити тип',
$lang{TREE}           = 'Загальні дерева',
$lang{ADD_SORT}       = 'Добавити сорт',
$lang{ADD_TREE}       = 'Добавити дерево',
$lang{SEARCH_TREE}    = 'Пошук дерева',

$lang{ADD_MESSEGES}   = 'Добавлено',
$lang{DEL_MESSEGES}   = 'Видалено',
$lang{EDIT_MESSEGES}  = 'Зміна',
$lang{SEARCH}         = 'Пошук',
$lang{CLEAR}          = 'Очистити',
$lang{SUC_SORT}       = 'Сорт добавлено в список',
$lang{DEL_SORT}       = 'Сорт видалено з списка',
$lang{EDIT_SORT}      = 'Ви намагаєтеся змінити данні',
$lang{ERROR_TYPE}     = 'Такого типу не існує',
$lang{ERROR}          = 'Помилка',

$lang{SUC_TYPE}       = 'Тип добавлено в список',
$lang{DEL_TYPE}       = 'Тип видалено з списка',

$lang{EXT_ID}         = 'Номер дерева',
$lang{AGE}            = 'Вік',
$lang{COORDX}         = 'Координата X',
$lang{COORDY}         = 'Координати Y',
$lang{STATUS}         = 'Статус',
$lang{COMMENT}        = 'Коментар',
$lang{SPECIES_ID}     = 'Номер на дереві',

1
