#!perl

=head1 NAME

  Timetracker

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Timetracker::db::Timetracker;
use Admins;
use XML::Simple qw(:strict);

use Abills::Fetcher qw/web_request/;
use Tree;

our ($html, %FORM, $db, %conf, $admin, %lang, @WEEKDAYS);
my  ($table);

sub tree_list {

  my $Tree = Tree->new($db, $admin, \%conf);
  my $positions_list = $Tree->position_list({ COLS_NAME => 1 });

  $html->tpl_show(_include('main_page_one', 'Tree'));

  ($table, $positions_list) = result_former({
    INPUT_DATA          => $Tree,
    LIST                => $positions_list,
    BASE_FIELDS         => 2,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, TYPE',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
    },
    SKIP_PAGES      => 1,
    TABLE           => {
      width   => '100%',
      caption => "$lang{LOGO}",
      qs      => $pages_qs,
      pages   => 500,
      ID      => 'TREES_ID',
    },
    MODULE    => 'Tree',
  });

  foreach my $line (@$positions_list) {
      my @fields_array = ();

      push @fields_array, $line->{"id"};
      push @fields_array, $line->{"type_of_tree"};
      $table->addrow(@fields_array);

    }
  print $table->show();

  return 1;
}


1;
