#!perl

=head1 NAME

  Trees

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Timetracker::db::Timetracker;
use Admins;
use XML::Simple qw(:strict);

use Abills::Fetcher qw/web_request/;
use Tree;

our ($html, %FORM, $db, %conf, $admin, %lang, @WEEKDAYS, $index);
my  ($table, $button_add, $button_change);

sub add_type {

  my $Tree = Tree->new($db, $admin, \%conf);
  my $type_list = $Tree->type_list({ COLS_NAME => 1 });

  if ($FORM{ADD}) {
    $Tree->add_type({%FORM});
    $html->message('info', 'Добавлено', 'Тип добавлено в список');
  } elsif ($FORM{del}) {
    $Tree->del_type({ID => $FORM{del} });
    $html->message('err', 'Видалено', 'Тип видалено з списка');
  } elsif ($FORM{CHANGE}) {
    $Tree->type_change(\%FORM);
    $html->message('warn', 'Змінити', 'Ви намагаєтеся змніти данні');
  }

  $button_add    = $html->form_input("ADD", $lang{ADD}, {TYPE => "submit"});
  $button_change = $html->form_input("CHANGE", $lang{CHANGE}, {TYPE => "submit"});

  ($table, $type_list) = result_former({
    INPUT_DATA          => $Tree,
    FUNCTION            => 'type_list',
    LIST                => $type_list,
    BASE_FIELDS         => 2,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, TYPE',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
    },
    SKIP_PAGES      => 1,
    TABLE           => {
      width   => '100%',
      caption => "$lang{LOGO}",
      qs      => $pages_qs,
      pages   => 500,
      ID      => 'TREES_ID',
    },
    MODULE    => 'Tree',
  });

  foreach my $line (@$type_list) {
      my @fields_array = ();

      push @fields_array, $line->{"id"};
      push @fields_array, $line->{"type_of_tree"};

      push @fields_array, ($html->button($lang{CHANGE}, "index=$index&id=$line->{id}&type_of_tree=$line->{type_of_tree}&CHANGE=1"._translate($line->{position}), { class => 'change' }));
      push @fields_array, ($html->button($lang{DELETE}, "index=$index&del=$line->{id}&type_of_tree=$line->{type_of_tree}"._translate($line->{position}), { class => 'del' }));

      $table->addrow(@fields_array);
    }

    $html->tpl_show(_include('main_page_one', 'Tree'), {
      ID            => $FORM{id},
      INDEX         => $index,
      ADD_TREE      => $html->form_input('TYPE_OF_TREE', $FORM{type_of_tree}),
      BUTTON_ADD    => $button_add,
      BUTTON_CHANGE => $button_change,
    });
  print $table->show();

  return 1;
}


1;
