#!perl

=head1 NAME

  Trees

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use Timetracker::db::Timetracker;
use Admins;
use XML::Simple qw(:strict);

use Abills::Fetcher qw/web_request/;
use Tree;
use Data::Dumper;

our ($html, %FORM, $db, %conf, $admin, %lang, @WEEKDAYS, $index);
my  ($table, $button_add, $button_change);

sub add_type {

  my $Tree = Tree->new($db, $admin, \%conf);
  my $type_list = $Tree->type_list({ COLS_NAME => 1 });

  if ($FORM{ADD}) {
    $Tree->add_type({%FORM});
    $html->message('info', $lang{ADD_MESSEGES}, $lang{SUC_SORT});
  } elsif ($FORM{del}) {
      $Tree->del_type({ID => $FORM{del} });
      $html->message('err', $lang{DEL_MESSEGES}, $lang{DEL_SORT});
  } elsif ($FORM{CHANGE}) {
      $Tree->type_change(\%FORM);
      $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_SORT});
  }

  $button_add    = $html->form_input("ADD", $lang{ADD}, {TYPE => "submit"});
  $button_change = $html->form_input("CHANGE", $lang{CHANGE}, {TYPE => "submit"});

  ($table, $type_list) = result_former({
    INPUT_DATA          => $Tree,
    FUNCTION            => 'type_list',
    LIST                => $type_list,
    BASE_FIELDS         => 2,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, TYPE',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
    },
    SKIP_PAGES      => 1,
    TABLE           => {
      width   => '100%',
      caption => "$lang{LOGO}",
      qs      => $pages_qs,
      pages   => 500,
      ID      => 'TREES_ID',
    },
    MODULE    => 'Tree',
  });

  foreach my $line (@$type_list) {
      my @fields_array = ();

      push @fields_array, $line->{"id"};
      push @fields_array, $line->{"type_of_tree"};

      push @fields_array, ($html->button($lang{CHANGE}, "index=$index&id=$line->{id}&type_of_tree=$line->{type_of_tree}&CHANGE=1"._translate($line->{position}), { class => 'change' }));
      push @fields_array, ($html->button($lang{DELETE}, "index=$index&del=$line->{id}&type_of_tree=$line->{type_of_tree}"._translate($line->{position}), { class => 'del' }));

      $table->addrow(@fields_array);
    }

  $html->tpl_show(_include('main_page_one', 'Tree'), {
      ID            => $FORM{id},
      INDEX         => $index,
      ADD_TREE      => $html->form_input('TYPE_OF_TREE', $FORM{type_of_tree}),
      BUTTON_ADD    => $button_add,
      BUTTON_CHANGE => $button_change,
    });

  print $table->show();

  return 1;
}

sub add_sort {
  my $Tree = Tree->new($db, $admin, \%conf);
  my $type_list   = $Tree->type_list({ COLS_NAME => 1});
  my $species     = $Tree->species_list({ COLS_NAME => 1});
  my @files = ();

  if ($FORM{ADD}) {
    $Tree->add_species({%FORM});
    $html->message('info', $lang{ADD_MESSEGES}, $lang{SUC_TYPE});
  } elsif ($FORM{del}) {
      $Tree->del_species({ID => $FORM{del} });
      $html->message('err', $lang{DEL_MESSEGES}, $lang{DEL_TYPE});
  } elsif ($FORM{CHANGE}) {
      $Tree->species_change(\%FORM);
      $html->message('warn', $lang{EDIT_MESSEGES}, $lang{EDIT_MESSEGES});
  }

  $button_add = $html->form_input("ADD", $lang{ADD}, {TYPE => "submit"});
  $button_change = $html->form_input("CHANGE", $lang{CHANGE}, {TYPE => "submit"});

  ($table, $species) = result_former({
    INPUT_DATA          => $Tree,
    FUNCTION            => 'species_list',
    LIST                => $species,
    BASE_FIELDS         => 3,
    SKIP_USER_TITLE     => 1,
    DEFAULT_FIELDS      => 'id, species, type_of_tree',
    EXT_TITLES          => {
      id                => $lang{ID},
      type_of_tree      => $lang{TYPE},
      species           => $lang{SPECIES},
    },
    SKIP_PAGES      => 1,
    TABLE           => {
      width   => '100%',
      caption => "$lang{LOGO}",
      qs      => $pages_qs,
      pages   => 500,
      ID      => 'TREES_ID',
    },
    MODULE    => 'Tree',
  });

  foreach my $line (@$species) {
    my @fields_array = ();

    push @fields_array, $line->{"id"};
    push @fields_array, $line->{"type_of_tree"};
    push @fields_array, $line->{"species"};

    push @fields_array, ($html->button($lang{CHANGE}, "index=$index&ID=$line->{id}&TYPE_ID=$line->{type_of_tree}&SPECIES=$line->{species}&CHANGE=1"._translate($line->{position}), { class => 'change' }));
    push @fields_array, ($html->button($lang{DELETE}, "index=$index&del=$line->{id}"._translate($line->{position}), { class => 'del' }));

    $table->addrow(@fields_array);
  }

  push @files, "--";
  foreach my $line (@$type_list) {
    push @files, $line->{"type_of_tree"};
  }
  $html->tpl_show(_include('main_page_two', 'Tree'), {
    TYPE_TREE   => $html->form_select(
      'TYPE_ID',
      {
        SELECTED     => $FORM{TYPE_ID},
        SEL_ARRAY    => \@files,
        ARRAY_NUM_ID => 1,
      }),
    ID              => $FORM{ID},
    INDEX           => $index,
    BUTTON_ADD      => $button_add,
    BUTTON_CHANGE   => $button_change,
    ADD_TREE_SORT   => $html->form_input('SPECIES', $FORM{species}),
  });

  print $table->show();

  return 1;
}

sub add_tree {
  $html->tpl_show(_include('main_page_three', 'Tree'));
}

1;
